const KeyCodes = {
	KEYCODE_ENTER: 66,
	KEYCODE_BACK: 4,
	KEYCODE_TAB: 61,
	KEYCODE_HOME: 3,
	KEYCODE_MENU: 82,
	KEYCODE_DEL: 67,
	KEYCODE_VOLUME_UP: 24,
	KEYCODE_VOLUME_DOWN: 25,
	KEYCODE_OK: 62,
};

export default KeyCodes;
